[package]
name = "TokenMessengerMinterV2"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
message_transmitter_v2 = "_"
token_messenger_minter_v2 = "_"
aptos_extensions = "_"
cctp_extensions = "_"
deployer = "_"

[dev-addresses]
message_transmitter_v2 = "0xebe6e5b8db973b4c8f5c3fbe7f5802e7a823b7ae4b70e5b6b1ce978418e5dad5"
token_messenger_minter_v2 = "0x4e0d4a160a8490565c7f61cd21531a320ccda0f55b9c7d20131b3717650db043"
aptos_extensions = "5ba1674a3ffa843ed88aa4a0a051b9a52f76459a8853e5cd62b22bcc488d2765"
cctp_extensions = "0x3fb43a8e43df7c06835ad18bd218d97e1dbe16a2b9980aa8045f55e52c18d86a"
deployer = "c06c5aa31d28c27be8345770a83b48314b829039ec5a33b79265216c13c66071"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "e2683170c2d7121ebe6174793dfc2f850992ca7b"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosExtensions]
local = "../../stablecoin-aptos/packages/aptos_extensions"

[dependencies.MessageTransmitterV2]
local = "../message_transmitter_v2"

[dependencies.CctpExtensions]
local = "../cctp_extensions"

[dev-dependencies]
